import { FoodLogEntry, FoodLibraryItem, Profile } from './types';

export const mockProfile: Profile = {
  id: 'mock-user-id',
  display_name: 'Ankur',
  daily_calorie_goal: 2000,
  daily_protein_goal: 120,
  daily_carbs_goal: 250,
  daily_fat_goal: 65,
  daily_fibre_goal: 30,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockTodayLogs: FoodLogEntry[] = [
  {
    id: '1',
    user_id: 'mock-user-id',
    food_library_id: 'lib-1',
    food_name: 'Scrambled eggs',
    quantity_g: 200,
    calories: 320,
    protein: 24,
    carbs: 2,
    fat: 22,
    fibre: 0,
    meal_type: 'breakfast',
    logged_date: new Date().toISOString().split('T')[0],
    status: 'confirmed',
    unit: 'g',
    image_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'mock-user-id',
    food_library_id: 'lib-2',
    food_name: 'Toast with butter',
    quantity_g: 60,
    calories: 185,
    protein: 4,
    carbs: 24,
    fat: 8,
    fibre: 1,
    meal_type: 'breakfast',
    logged_date: new Date().toISOString().split('T')[0],
    status: 'confirmed',
    unit: 'g',
    image_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: 'mock-user-id',
    food_library_id: 'lib-3',
    food_name: 'Banana',
    quantity_g: 120,
    calories: 105,
    protein: 1,
    carbs: 27,
    fat: 0,
    fibre: 3,
    meal_type: 'snack',
    logged_date: new Date().toISOString().split('T')[0],
    status: 'confirmed',
    unit: 'g',
    image_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    user_id: 'mock-user-id',
    food_library_id: null,
    food_name: 'Chicken pasta',
    quantity_g: 350,
    calories: null,
    protein: null,
    carbs: null,
    fat: null,
    fibre: null,
    meal_type: 'lunch',
    logged_date: new Date().toISOString().split('T')[0],
    status: 'processing',
    unit: 'g',
    image_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockFrequentFoods = [
  { name: 'Scrambled eggs', detail: '200g', calories: 320, image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=400&fit=crop&q=80' },
  { name: 'Toast with butter', detail: '60g', calories: 185, image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop&q=80' },
  { name: 'Banana', detail: '120g', calories: 105, image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop&q=80' },
  { name: 'Coffee with milk', detail: '250ml', calories: 45, image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop&q=80' },
];

export const mockFoodLibrary: Record<string, FoodLibraryItem> = {
  'lib-1': {
    id: 'lib-1',
    name: 'Scrambled eggs',
    calories_per_100g: 160,
    protein_per_100g: 12,
    carbs_per_100g: 1,
    fat_per_100g: 11,
    fibre_per_100g: 0,
    serving_size_g: 200,
    source: 'base',
    unit: 'g',
    image_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  'lib-2': {
    id: 'lib-2',
    name: 'Toast with butter',
    calories_per_100g: 308,
    protein_per_100g: 7,
    carbs_per_100g: 40,
    fat_per_100g: 13,
    fibre_per_100g: 2,
    serving_size_g: 60,
    source: 'base',
    unit: 'g',
    image_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  'lib-3': {
    id: 'lib-3',
    name: 'Banana',
    calories_per_100g: 88,
    protein_per_100g: 1,
    carbs_per_100g: 23,
    fat_per_100g: 0,
    fibre_per_100g: 3,
    serving_size_g: 120,
    source: 'base',
    unit: 'g',
    image_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
};

export const foodImages: Record<string, string> = {
  'Scrambled eggs': 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=400&fit=crop&q=80',
  'Toast with butter': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop&q=80',
  'Banana': 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop&q=80',
  'Chicken pasta': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=400&fit=crop&q=80',
  'Coffee with milk': 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop&q=80',
};
